spring:
    application:
        name: mall
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/mall
        username: root
        password: 123456
    thymeleaf:
        cache: false
        prefix: classpath:/template/
        suffix: .html
    web:
        resources:
            static-locations: classpath:/static/
server:
    port: 8000
mybatis:
    mapper-locations: classpath:mapper/*.xml
